<header>
     <h1>CameoAudio | Your event equipment specialist</h1>
     <nav id="navv">
         <a href="index.php">Home</a> 
         <a href="product.php">Product Range</a> 
         <a href="enquire.php">Product Enquiry / Order</a> 
         <a href="about.php">About</a>
         <a href="enhancements.php">Enhancements 1</a>
         <a href="enhancements2.php">Enhancements 2</a>
         <a href="enhancements3.php">Enhancements 3</a>
         <a href="login.php">Manage Orders</a>
      </nav>
    <br />
    <img src="images/mylogo.png" alt="CameoAudio logo" id="logo">
      <hr />
</header>